# Generated by Django 3.2 on 2021-04-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resortname', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('noofrooms', models.CharField(max_length=30)),
                ('cost', models.CharField(max_length=30)),
                ('availability', models.CharField(max_length=30)),
                ('safty', models.CharField(max_length=30)),
                ('activities', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=30)),
                ('facilities', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='')),
                ('username', models.CharField(max_length=30)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apperesort.state')),
            ],
        ),
    ]
