# Generated by Django 3.2 on 2021-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0005_managerregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresorts',
            name='map',
            field=models.CharField(default=33, max_length=100),
            preserve_default=False,
        ),
    ]
