# Generated by Django 3.2 on 2021-04-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0006_addresorts_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresorts',
            name='map',
            field=models.CharField(max_length=500),
        ),
    ]
