# Generated by Django 3.2 on 2021-04-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0007_alter_addresorts_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('resortdetails', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=10)),
                ('resortname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apperesort.addresorts')),
            ],
        ),
    ]
