# Generated by Django 3.2 on 2021-05-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0008_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='')),
                ('resortname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apperesort.addresorts')),
            ],
        ),
    ]
