# Generated by Django 3.2 on 2021-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
    ]
