# Generated by Django 3.2 on 2021-05-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0010_image_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='resortname',
        ),
    ]
