# Generated by Django 3.2 on 2021-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0011_remove_image_resortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('acnonac', models.CharField(max_length=10)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('checkin', models.CharField(max_length=10)),
                ('checkout', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
