# Generated by Django 3.2 on 2021-05-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0012_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=23, max_length=10),
            preserve_default=False,
        ),
    ]
