# Generated by Django 3.2 on 2021-05-27 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0013_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='resortname',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='apperesort.addresorts'),
            preserve_default=False,
        ),
    ]
