# Generated by Django 3.2 on 2021-06-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apperesort', '0014_booking_resortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='valid',
            field=models.CharField(default=33, max_length=10),
            preserve_default=False,
        ),
    ]
