from django.db import models

# Create your models here.
class State(models.Model):
    state=models.CharField(max_length=30)
class Login(models.Model):
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=30)
    status=models.IntegerField()
class User(models.Model):
    name=models.CharField(max_length=30)
    address=models.CharField(max_length=30)
    state=models.ForeignKey(State, on_delete=models.CASCADE)
    city=models.CharField(max_length=30)
    pincode=models.IntegerField()
    email=models.CharField(max_length=30)
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=30)
    photo=models.FileField()
class Addresorts(models.Model):
    resortname=models.CharField(max_length=30)
    place=models.CharField(max_length=30)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    noofrooms=models.CharField(max_length=30)
    cost=models.CharField(max_length=30)
    availability=models.CharField(max_length=30)
    safty=models.CharField(max_length=30)
    activities=models.CharField(max_length=30)
    des=models.CharField(max_length=30)
    facilities=models.CharField(max_length=30)
    photo = models.FileField()
    map=models.CharField(max_length=500)
    username=models.CharField(max_length=30)
class Managerregister(models.Model):
    name=models.CharField(max_length=30)
    dob=models.DateTimeField()
    gender=models.CharField(max_length=30)
    phone=models.IntegerField()
    address=models.CharField(max_length=30)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    city=models.CharField(max_length=30)
    pincode=models.IntegerField()
    resortname=models.CharField(max_length=30)
    place=models.CharField(max_length=30)
    designation=models.CharField(max_length=30)
    photo=models.FileField()
    username=models.CharField(max_length=30)
    password=models.CharField(max_length=30)
class Feedback(models.Model):
    username= models.CharField(max_length=30)
    resortdetails= models.CharField(max_length=30)
    resortname=models.ForeignKey(Addresorts, on_delete=models.CASCADE)
    comment = models.CharField(max_length=30)
    rating=models.CharField(max_length=10)
class Image(models.Model):
    username = models.CharField(max_length=30)
    title= models.CharField(max_length=30)
    photo = models.FileField()
class Booking(models.Model):
    type= models.CharField(max_length=10)
    acnonac= models.CharField(max_length=10)
    resortname = models.ForeignKey(Addresorts, on_delete=models.CASCADE)
    adult= models.IntegerField()
    child= models.IntegerField()
    checkin=models.CharField(max_length=10)
    checkout = models.CharField(max_length=10)
    username=models.CharField(max_length=30)
    status = models.CharField(max_length=10)
    valid = models.CharField(max_length=10)